services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
      - 8888:8888
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local
    restart: unless-stopped
    depends_on:
      - backend
