services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
      - 8888:8888
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local
    restart: unless-stopped
    depends_on:
      - backend

  redis:
    image: redis:8.8.0-alpine
    container_name: gateway-redis
    ports:
      - "6379:6379"
    volumes:
       - redis_data:/data
     restart: unless-stopped
