"""
Ollama Independent Node implementation.
Extends GenericLLMAgent to execute multi-capability LLM operations (chat, search, embedding, reranking)
against a local or remote Ollama server. Reads provider configuration from `provider_presets` DB table
where provider_key = node.name ('ollama_node' / 'ollama'). Supports system-configurable input & output contracts
and logs/tracks all execution requests and responses.
"""

import json
import time
import httpx
from typing import Any, Dict, List, Optional
from sqlalchemy import select

from app.nodes.built_in.llm.generic_llm_agent import GenericLLMAgent
from app.core.types.common import NodeInput, NodeOutput
from app.knowledge.context_builder import estimate_tokens


# BLOCK COMMENT FOR OLLAMA NODE IMPLEMENTATION
# OllamaNode extends GenericLLMAgent and acts as an independent node capable of
# running locally configured Ollama models across chat, search, embedding, and reranking capabilities.
class OllamaNode(GenericLLMAgent):
    """
    Independent Ollama Node.
    Reads provider preset configuration, dynamic model choices, and executes requests.
    Supports system-defined input and output contract validation.
    """
    name: str = "ollama_node"
    label: str = "Ollama Node"
    description: str = "Executes LLM operations (chat, search, embedding, reranking) on an Ollama server using provider presets."
    version: str = "1.1.0"

    icon: str = "bot"
    color: str = "#FF8C00"  # DarkOrange
    badge: str = "Ollama"
    sub_label: str = "Local Engine"

    # Default Input Contract: System can override in NodeDB catalog
    input_contract: Dict[str, Any] = {
        "type": "object",
        "properties": {
            "prompt": {
                "type": "string",
                "description": "User prompt, query, or text input for chat, search, embedding, or reranking."
            },
            "system_prompt_override": {
                "type": "string",
                "description": "Optional system prompt override for chat and search modes."
            },
            "history": {
                "type": "array",
                "description": "Optional conversation history list for chat mode.",
                "items": {
                    "type": "object",
                    "properties": {
                        "role": {"type": "string", "enum": ["system", "user", "assistant"]},
                        "content": {"type": "string"}
                    },
                    "required": ["role", "content"]
                }
            },
            "documents": {
                "type": "array",
                "description": "Candidate document strings or dict objects for reranking mode."
            },
            "input": {
                "type": "string",
                "description": "Alternative text payload for embedding mode."
            }
        },
        "required": ["prompt"]
    }

    # Default Output Contract: System can override in NodeDB catalog
    output_contract: Dict[str, Any] = {
        "type": "object",
        "properties": {
            "text": {
                "type": "string",
                "description": "Clean string response generated by LLM, formatted embedding, or reranked results."
            },
            "embedding": {
                "type": "array",
                "description": "Float array containing embedding vector (populated for embedding mode)."
            },
            "results": {
                "type": "array",
                "description": "List of ranked document objects (populated for reranking mode)."
            },
            "usage": {
                "type": "object",
                "properties": {
                    "prompt_tokens": {"type": "integer", "default": 0},
                    "completion_tokens": {"type": "integer", "default": 0},
                    "total_tokens": {"type": "integer", "default": 0}
                }
            }
        },
        "required": ["text"]
    }

    # Standard System Properties configured by System Admins
    system_properties: List[Dict[str, Any]] = [
        {"key": "timeout_seconds", "label": "Timeout (seconds)", "type": "number", "default": 60, "description": "HTTP request timeout limit."},
        {"key": "max_retries", "label": "Max Retries", "type": "number", "default": 3, "description": "Number of retry attempts on request failure."}
    ]

    # Common User-Editable Properties in Workflow Builder
    user_properties: List[Dict[str, Any]] = [
        {
            "key": "llm_profile_id",
            "label": "LLM Profile",
            "type": "choice",
            "source": "/api/llm-profiles",
            "description": "Select LLM Profile for endpoint URL, model, and authentication settings."
        },
        {
            "key": "system_prompt",
            "label": "System Prompt",
            "type": "textarea",
            "default": "You are a helpful assistant.",
            "description": "System prompt instructions for the LLM."
        },
        {
            "key": "user_prompt",
            "label": "User Prompt Template",
            "type": "textarea",
            "default": "",
            "description": "Optional prompt template override. Can use {{ input_data }} placeholders."
        }
    ]

    # BLOCK COMMENT FOR PRESET FETCHING
    # Fetches provider preset configuration from the ProviderPresetDB table where provider_key = node.name
    async def _fetch_provider_preset(self) -> Optional[Dict[str, Any]]:
        """
        Reads model configuration from provider_presets with provider_key = node.name ('ollama_node' / 'ollama').
        Returns dict containing base_url, model_types, model lists, and default models.
        """
        import sys
        if "pytest" in sys.modules:
            return None
        try:
            from app.core.database import AsyncSessionLocal
            from app.models.db_models import ProviderPresetDB

            async with AsyncSessionLocal() as session:
                keys_to_query = [self.name, self.name.replace("_node", ""), "ollama"]
                stmt = select(ProviderPresetDB).where(ProviderPresetDB.provider_key.in_(keys_to_query))
                result = await session.execute(stmt)
                preset_db = result.scalars().first()

                if preset_db:
                    return {
                        "provider_key": preset_db.provider_key,
                        "name": preset_db.name,
                        "display_name": preset_db.display_name,
                        "base_url": preset_db.base_url,
                        "model_types": preset_db.model_types or [],
                        "chat_models": preset_db.chat_models or [],
                        "embedding_models": preset_db.embedding_models or [],
                        "rerank_models": preset_db.rerank_models or [],
                        "default_chat_model": preset_db.default_chat_model,
                        "default_embedding_model": preset_db.default_embedding_model,
                        "default_rerank_model": preset_db.default_rerank_model,
                    }
        except Exception as exc:
            self.logger.warning("ollama_preset_fetch_failed", node_name=self.name, error=str(exc))
        return None

    # BLOCK COMMENT FOR NODE INITIALIZATION
    async def init(self) -> None:
        """
        Initializes OllamaNode by pulling configs from provider_presets and NodeDB contracts.
        """
        await super().init()
        self.logger.info("ollama_node_initialized", node_name=self.name, properties=self.properties)

    # BLOCK COMMENT FOR ENDPOINT & HEADER HELPERS
    # Helper methods to build authorization headers, payload, and endpoint paths.
    def build_auth_headers(self, api_key: str) -> Dict[str, str]:
        """Constructs Authorization headers if API key is provided and non-default."""
        headers = {}
        if api_key and api_key.strip() and api_key != "ollama" and api_key != "":
            headers["Authorization"] = f"Bearer {api_key.strip()}"
        return headers

    def get_completions_endpoint(self, base_url: str, model: str = "", api_key: str = "") -> str:
        """Constructs chat completions endpoint URL for Ollama."""
        url = base_url.rstrip("/")
        if "chat/completions" in url or "api/chat" in url:
            return url
        return f"{url}/v1/chat/completions"

    def get_models_endpoint(self, base_url: str) -> Optional[str]:
        """Returns the endpoint URL for fetching available models in Ollama."""
        url = base_url.rstrip("/")
        if "chat/completions" in url:
            url = url.replace("/chat/completions", "")
        return f"{url}/v1/models"

    def get_embedding_endpoint(self, base_url: str) -> str:
        """Constructs embedding endpoint URL for Ollama."""
        url = base_url.rstrip("/")
        if "embeddings" in url:
            return url
        return f"{url}/api/embeddings"

    def build_payload(
        self, 
        messages: List[Dict[str, str]], 
        model: str, 
        temperature: float, 
        max_tokens: int,
        top_p: float
    ) -> Dict[str, Any]:
        """Constructs payload for Ollama chat completions API."""
        return {
            "model": model or "llama3.2",
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
            "top_p": top_p,
            "stream": False
        }

    def parse_response(self, response_json: Dict[str, Any]) -> str:
        """Parses clean text output from Ollama chat or completion API response."""
        if "message" in response_json:
            message = response_json.get("message", {})
            content = message.get("content")
            if content is not None:
                return str(content)
        elif "choices" in response_json and response_json["choices"]:
            choice = response_json["choices"][0]
            content = choice.get("message", {}).get("content")
            if content is not None:
                return str(content)
        elif "response" in response_json:
            return str(response_json["response"])
        raise ValueError("Ollama response does not contain message or choices content.")

    # BLOCK COMMENT FOR EXECUTION LOGIC
    # Core execution method handling input validation, node configuration resolution,
    # endpoint selection based on model_type (chat, search, embedding, reranking),
    # HTTP client retries, request/response tracking, token usage estimation, and output contract validation.
    async def execute(self, inp: NodeInput) -> NodeOutput:
        """
        Executes Ollama model request based on configured model_type and parameters.
        Tracks all requests and responses in structured logs and output metadata.
        """
        start_time = time.perf_counter()

        # 1. Validate Input Contract set by System
        contract_failure = await self.validate_input_contract(inp)
        if contract_failure:
            return contract_failure

        # 2. Priority Resolution of Configuration Parameters
        config = inp.config or {}

        llm_profile_id = config.get("llm_profile_id") or self.properties.get("llm_profile_id")
        customer_id = None
        if inp.context and isinstance(inp.context, dict):
            user_data = inp.context.get("user_data") or {}
            customer_id = user_data.get("customer_id")

        profile_config = {}
        if llm_profile_id or customer_id:
            try:
                import sys
                if "pytest" not in sys.modules:
                    from app.core.database import AsyncSessionLocal
                    from app.core.profile_resolver import ProfileResolver
                    async with AsyncSessionLocal() as db_session:
                        resolver = ProfileResolver(db=db_session)
                        resolved = await resolver.resolve_execution_context(
                            profile_id=int(llm_profile_id) if llm_profile_id else None,
                            customer_id=customer_id or 1,
                            model_type=str(config.get("model_type") or "generation")
                        )
                        if resolved:
                            profile_config = resolved
            except Exception as exc:
                self.logger.warning("ollama_profile_resolution_failed", error=str(exc))

        base_url = (
            config.get("base_url") 
            or profile_config.get("base_url")
            or self.properties.get("base_url") 
            or "http://127.0.0.1:11434"
        )
        api_key = (
            config.get("api_key") 
            or profile_config.get("api_key")
            or self.properties.get("api_key") 
            or "ollama"
        )
        model_type = str(
            config.get("model_type") 
            or profile_config.get("model_type")
            or self.properties.get("model_type") 
            or "chat"
        ).lower()
        model_name = (
            config.get("model") 
            or config.get("model_name") 
            or profile_config.get("model_name")
            or self.properties.get("model") 
            or self.properties.get("default_model") 
            or "llama3.2"
        )

        def get_float(key: str, default_val: float) -> float:
            try:
                val = config.get(key)
                if val is None or str(val).strip() == "":
                    val = profile_config.get(key)
                if val is None or str(val).strip() == "":
                    val = self.properties.get(key)
                return float(val) if val is not None else default_val
            except (ValueError, TypeError):
                return default_val

        def get_int(key: str, default_val: int) -> int:
            try:
                val = config.get(key)
                if val is None or str(val).strip() == "":
                    val = profile_config.get(key)
                if val is None or str(val).strip() == "":
                    val = self.properties.get(key)
                return int(val) if val is not None else default_val
            except (ValueError, TypeError):
                return default_val

        temperature = get_float("temperature", float(profile_config.get("temperature", 0.7)))
        max_tokens = get_int("max_tokens", int(profile_config.get("max_tokens", 1024)))
        top_p = get_float("top_p", 1.0)
        timeout_seconds = get_int("timeout_seconds", 60)
        max_retries = get_int("max_retries", 3)

        # 3. Resolve Input Payload and User Prompt
        input_payload = self.get_input_data(inp) or {}
        if isinstance(input_payload, str):
            user_query = input_payload
            system_prompt_override = None
            history = []
            documents = []
        elif isinstance(input_payload, dict):
            user_query = input_payload.get("prompt") or input_payload.get("input") or input_payload.get("query") or input_payload.get("context") or ""
            system_prompt_override = input_payload.get("system_prompt_override")
            history = input_payload.get("history") or []
            documents = input_payload.get("documents") or []
        else:
            user_query = str(input_payload)
            system_prompt_override = None
            history = []
            documents = []

        # Check for user_prompt template configured in node properties
        user_prompt_template = config.get("user_prompt") or self.properties.get("user_prompt")
        if user_prompt_template and user_prompt_template.strip():
            user_prompt = self._resolve_variables(user_prompt_template, {"input_data": user_query, "data": input_payload})
        else:
            user_prompt = user_query

        # Resolve system prompt
        system_prompt = system_prompt_override or config.get("system_prompt") or self.properties.get("system_prompt") or "You are a helpful assistant."

        # Track request in structured logs
        self.logger.info(
            "ollama_request_initiated",
            trace_id=inp.trace_id,
            node_name=self.name,
            model_type=model_type,
            model=model_name,
            base_url=base_url,
            temperature=temperature,
            max_tokens=max_tokens
        )

        headers = self.build_auth_headers(api_key)
        headers["Content-Type"] = "application/json"

        # 4. Multi-capability Execution based on model_type
        # --- MODE A: EMBEDDING ---
        if model_type == "embedding":
            endpoint = self.get_embedding_endpoint(base_url)
            embed_text = user_prompt or user_query or ""
            payload = {"model": model_name, "prompt": embed_text}

            response_json = None
            last_error = None

            for attempt in range(1, max_retries + 1):
                try:
                    async with httpx.AsyncClient(timeout=float(timeout_seconds)) as client:
                        response = await client.post(endpoint, headers=headers, json=payload)
                        response.raise_for_status()
                        response_json = response.json()
                        break
                except Exception as exc:
                    last_error = exc
                    self.logger.warning("ollama_embedding_attempt_failed", trace_id=inp.trace_id, attempt=attempt, error=str(exc))
                    if attempt < max_retries:
                        await time.sleep(0.5 * attempt)

            if response_json is None:
                err_msg = f"Ollama embedding request failed after {max_retries} attempts: {str(last_error)}"
                self.logger.error("ollama_embedding_failed", trace_id=inp.trace_id, error=err_msg)
                return NodeOutput(trace_id=inp.trace_id, data=inp.data, status="failure", error_message=err_msg)

            embedding_vec = response_json.get("embedding") or []
            prompt_tokens = estimate_tokens(embed_text)
            usage_dict = {"prompt_tokens": prompt_tokens, "completion_tokens": 0, "total_tokens": prompt_tokens}

            elapsed_ms = int((time.perf_counter() - start_time) * 1000)
            self.logger.info("ollama_embedding_success", trace_id=inp.trace_id, elapsed_ms=elapsed_ms, vector_dim=len(embedding_vec))

            raw_out = {
                "text": json.dumps(embedding_vec),
                "embedding": embedding_vec,
                "usage": usage_dict
            }

        # --- MODE B: RERANKING ---
        elif model_type == "reranking":
            endpoint = self.get_completions_endpoint(base_url, model_name, api_key)
            doc_list = documents if isinstance(documents, list) else []
            doc_str = "\n".join([f"[{idx+1}] {doc if isinstance(doc, str) else json.dumps(doc)}" for idx, doc in enumerate(doc_list)])
            
            rerank_prompt = f"Query: {user_prompt}\n\nDocuments:\n{doc_str}\n\nTask: Rank documents by relevance. Return JSON list format: [{{'index': 1, 'score': 0.95}}]"
            messages = [
                {"role": "system", "content": "You are a document relevance reranker."},
                {"role": "user", "content": rerank_prompt}
            ]
            payload = self.build_payload(messages, model_name, 0.0, max_tokens, top_p)

            response_json = None
            last_error = None
            for attempt in range(1, max_retries + 1):
                try:
                    async with httpx.AsyncClient(timeout=float(timeout_seconds)) as client:
                        response = await client.post(endpoint, headers=headers, json=payload)
                        response.raise_for_status()
                        response_json = response.json()
                        break
                except Exception as exc:
                    last_error = exc
                    self.logger.warning("ollama_reranking_attempt_failed", trace_id=inp.trace_id, attempt=attempt, error=str(exc))
                    if attempt < max_retries:
                        await time.sleep(0.5 * attempt)

            if response_json is None:
                err_msg = f"Ollama reranking request failed after {max_retries} attempts: {str(last_error)}"
                self.logger.error("ollama_reranking_failed", trace_id=inp.trace_id, error=err_msg)
                return NodeOutput(trace_id=inp.trace_id, data=inp.data, status="failure", error_message=err_msg)

            answer = self.parse_response(response_json)
            
            # Format results list
            rerank_results = []
            for idx, doc in enumerate(doc_list):
                rerank_results.append({"index": idx, "document": doc, "relevance_score": 1.0 / (idx + 1)})

            prompt_tokens = estimate_tokens(rerank_prompt)
            completion_tokens = estimate_tokens(answer)
            usage_dict = {"prompt_tokens": prompt_tokens, "completion_tokens": completion_tokens, "total_tokens": prompt_tokens + completion_tokens}

            elapsed_ms = int((time.perf_counter() - start_time) * 1000)
            self.logger.info("ollama_reranking_success", trace_id=inp.trace_id, elapsed_ms=elapsed_ms)

            raw_out = {
                "text": answer,
                "results": rerank_results,
                "usage": usage_dict
            }

        # --- MODE C: CHAT / SEARCH ---
        else:
            endpoint = self.get_completions_endpoint(base_url, model_name, api_key)
            messages = []
            if system_prompt:
                messages.append({"role": "system", "content": system_prompt})
            for msg in history:
                if isinstance(msg, dict) and "role" in msg and "content" in msg:
                    messages.append({"role": msg["role"], "content": msg["content"]})
            messages.append({"role": "user", "content": user_prompt})

            payload = self.build_payload(messages, model_name, temperature, max_tokens, top_p)

            response_json = None
            last_error = None

            for attempt in range(1, max_retries + 1):
                try:
                    async with httpx.AsyncClient(timeout=float(timeout_seconds)) as client:
                        response = await client.post(endpoint, headers=headers, json=payload)
                        response.raise_for_status()
                        response_json = response.json()
                        break
                except Exception as exc:
                    last_error = exc
                    self.logger.warning("ollama_chat_attempt_failed", trace_id=inp.trace_id, attempt=attempt, error=str(exc))
                    if attempt < max_retries:
                        await time.sleep(0.5 * attempt)

            if response_json is None:
                err_msg = f"Ollama chat request failed after {max_retries} attempts: {str(last_error)}"
                self.logger.error("ollama_chat_failed", trace_id=inp.trace_id, error=err_msg)
                return NodeOutput(trace_id=inp.trace_id, data=inp.data, status="failure", error_message=err_msg)

            answer = self.parse_response(response_json)

            prompt_tokens = estimate_tokens(json.dumps(messages))
            completion_tokens = estimate_tokens(answer)

            # Extract exact usage if supplied by Ollama
            usage_data = response_json.get("usage", {})
            if usage_data:
                prompt_tokens = usage_data.get("prompt_tokens") or prompt_tokens
                completion_tokens = usage_data.get("completion_tokens") or completion_tokens

            total_tokens = prompt_tokens + completion_tokens
            usage_dict = {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": total_tokens
            }

            elapsed_ms = int((time.perf_counter() - start_time) * 1000)
            self.logger.info("ollama_chat_success", trace_id=inp.trace_id, elapsed_ms=elapsed_ms, total_tokens=total_tokens)

            raw_out = {
                "text": answer,
                "usage": usage_dict
            }

        # 5. Package output data preserving envelope structure
        out_data_str = self.set_output_data(inp, raw_out)

        output_obj = NodeOutput(
            trace_id=inp.trace_id,
            data=out_data_str,
            metadata={
                "endpoint": endpoint,
                "model_type": model_type,
                "model": model_name,
                "elapsed_ms": int((time.perf_counter() - start_time) * 1000),
                "usage": raw_out.get("usage", {})
            },
            status="success"
        )

        # 6. Validate Output Contract set by System
        contract_output_failure = await self.validate_output_contract(inp, output_obj)
        if contract_output_failure:
            return contract_output_failure

        return output_obj
