[project]
name = "enterprise-llm-gateway"
version = "0.2.3"
description = "Enterprise-grade LLM Gateway with LangGraph workflows, observability, and guardrails."
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-dotenv",
    "pydantic>=2.0",
    "pydantic-settings",
    "redis>=4.2.0",
    "structlog",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-httpx",
    "prometheus-fastapi-instrumentator",
    "langgraph",
    "langchain",
    "spacy",
    "rich",
    "langchain-openai",
    "presidio_anonymizer",
    "presidio_analyzer",
    "httpx"
]