from enum import Enum


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobType(str, Enum):
    DOCUMENT_INDEX = "DOCUMENT_INDEX"
    DOCUMENT_REINDEX = "DOCUMENT_REINDEX"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    WORKFLOW_EXECUTION = "WORKFLOW_EXECUTION"
    CONNECTOR_SYNC = "CONNECTOR_SYNC"
    IMPORT = "IMPORT"
    EXPORT = "EXPORT"


class EntityType(str, Enum):
    DOCUMENT = "DOCUMENT"

    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"

    WORKFLOW = "WORKFLOW"

    CONNECTOR = "CONNECTOR"

    AGENT = "AGENT"

    MODEL = "MODEL"
